# Setup
title           : Experiments
description     : "CSS and Javascript experiments"
keywords        : "lefoy css javascript experiments"
url             : http://lefoy.net/experiments
repo            : https://github.com/lefoy/experiments

author          : lefoy
name            : "lefoy"
website         : http://lefoy.net/
github          : https://github.com/lefoy
twitter         : https://twitter.com/louisetiennefoy
stackoverflow   : http://stackoverflow.com/users/2141535/lefoy?tab=summary

version         : 1.0.0
markdown        : redcarpet
highlighter     : pygments
#permalink       : /experiments/:categories/:year/:month/:day/:title.html

# Assets
sass:
  sass_dir: _scss
  style: :compressed
